import { type MigrateDownArgs, type MigrateUpArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "payload"."enum_pages_blocks_hero_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_pages_blocks_hero_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_pages_blocks_hero_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_pages_blocks_rich_text_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_pages_blocks_rich_text_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_pages_blocks_rich_text_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_pages_blocks_image_text_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_pages_blocks_image_text_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_pages_blocks_image_text_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_pages_blocks_card_grid_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_pages_blocks_card_grid_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_pages_blocks_card_grid_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_pages_blocks_card_grid_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "payload"."enum_pages_blocks_product_grid_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_pages_blocks_product_grid_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_pages_blocks_product_grid_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_pages_blocks_product_grid_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "payload"."enum_pages_blocks_gallery_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_pages_blocks_gallery_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_pages_blocks_gallery_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_pages_blocks_gallery_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "payload"."enum_pages_blocks_downloads_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_pages_blocks_downloads_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_pages_blocks_downloads_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_pages_blocks_downloads_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "payload"."enum_pages_blocks_spec_table_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_pages_blocks_spec_table_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_pages_blocks_spec_table_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_pages_blocks_call_to_action_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_pages_blocks_call_to_action_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_pages_blocks_call_to_action_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_posts_blocks_hero_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_posts_blocks_hero_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_posts_blocks_hero_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_posts_blocks_rich_text_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_posts_blocks_rich_text_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_posts_blocks_rich_text_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_posts_blocks_image_text_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_posts_blocks_image_text_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_posts_blocks_image_text_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_posts_blocks_card_grid_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_posts_blocks_card_grid_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_posts_blocks_card_grid_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_posts_blocks_card_grid_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "payload"."enum_posts_blocks_product_grid_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_posts_blocks_product_grid_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_posts_blocks_product_grid_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_posts_blocks_product_grid_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "payload"."enum_posts_blocks_gallery_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_posts_blocks_gallery_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_posts_blocks_gallery_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_posts_blocks_gallery_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "payload"."enum_posts_blocks_downloads_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_posts_blocks_downloads_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_posts_blocks_downloads_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_posts_blocks_downloads_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "payload"."enum_posts_blocks_spec_table_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_posts_blocks_spec_table_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_posts_blocks_spec_table_alignment" AS ENUM('left', 'center');
  CREATE TYPE "payload"."enum_posts_blocks_call_to_action_background_style" AS ENUM('default', 'panel', 'soft', 'contrast');
  CREATE TYPE "payload"."enum_posts_blocks_call_to_action_spacing" AS ENUM('compact', 'normal', 'spacious');
  CREATE TYPE "payload"."enum_posts_blocks_call_to_action_alignment" AS ENUM('left', 'center');
  ALTER TABLE "payload"."pages_blocks_hero" ADD COLUMN "background_style" "payload"."enum_pages_blocks_hero_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_hero" ADD COLUMN "spacing" "payload"."enum_pages_blocks_hero_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_hero" ADD COLUMN "alignment" "payload"."enum_pages_blocks_hero_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_rich_text" ADD COLUMN "background_style" "payload"."enum_pages_blocks_rich_text_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_rich_text" ADD COLUMN "spacing" "payload"."enum_pages_blocks_rich_text_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_rich_text" ADD COLUMN "alignment" "payload"."enum_pages_blocks_rich_text_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_image_text" ADD COLUMN "background_style" "payload"."enum_pages_blocks_image_text_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_image_text" ADD COLUMN "spacing" "payload"."enum_pages_blocks_image_text_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_image_text" ADD COLUMN "alignment" "payload"."enum_pages_blocks_image_text_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_card_grid" ADD COLUMN "background_style" "payload"."enum_pages_blocks_card_grid_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_card_grid" ADD COLUMN "spacing" "payload"."enum_pages_blocks_card_grid_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_card_grid" ADD COLUMN "alignment" "payload"."enum_pages_blocks_card_grid_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_card_grid" ADD COLUMN "columns" "payload"."enum_pages_blocks_card_grid_columns" DEFAULT '3' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_product_grid" ADD COLUMN "background_style" "payload"."enum_pages_blocks_product_grid_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_product_grid" ADD COLUMN "spacing" "payload"."enum_pages_blocks_product_grid_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_product_grid" ADD COLUMN "alignment" "payload"."enum_pages_blocks_product_grid_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_product_grid" ADD COLUMN "columns" "payload"."enum_pages_blocks_product_grid_columns" DEFAULT '3' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_gallery" ADD COLUMN "background_style" "payload"."enum_pages_blocks_gallery_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_gallery" ADD COLUMN "spacing" "payload"."enum_pages_blocks_gallery_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_gallery" ADD COLUMN "alignment" "payload"."enum_pages_blocks_gallery_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_gallery" ADD COLUMN "columns" "payload"."enum_pages_blocks_gallery_columns" DEFAULT '3' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_downloads" ADD COLUMN "background_style" "payload"."enum_pages_blocks_downloads_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_downloads" ADD COLUMN "spacing" "payload"."enum_pages_blocks_downloads_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_downloads" ADD COLUMN "alignment" "payload"."enum_pages_blocks_downloads_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_downloads" ADD COLUMN "columns" "payload"."enum_pages_blocks_downloads_columns" DEFAULT '3' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_spec_table" ADD COLUMN "background_style" "payload"."enum_pages_blocks_spec_table_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_spec_table" ADD COLUMN "spacing" "payload"."enum_pages_blocks_spec_table_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_spec_table" ADD COLUMN "alignment" "payload"."enum_pages_blocks_spec_table_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_call_to_action" ADD COLUMN "background_style" "payload"."enum_pages_blocks_call_to_action_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_call_to_action" ADD COLUMN "spacing" "payload"."enum_pages_blocks_call_to_action_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."pages_blocks_call_to_action" ADD COLUMN "alignment" "payload"."enum_pages_blocks_call_to_action_alignment" DEFAULT 'center' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_hero" ADD COLUMN "background_style" "payload"."enum_posts_blocks_hero_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_hero" ADD COLUMN "spacing" "payload"."enum_posts_blocks_hero_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_hero" ADD COLUMN "alignment" "payload"."enum_posts_blocks_hero_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_rich_text" ADD COLUMN "background_style" "payload"."enum_posts_blocks_rich_text_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_rich_text" ADD COLUMN "spacing" "payload"."enum_posts_blocks_rich_text_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_rich_text" ADD COLUMN "alignment" "payload"."enum_posts_blocks_rich_text_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_image_text" ADD COLUMN "background_style" "payload"."enum_posts_blocks_image_text_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_image_text" ADD COLUMN "spacing" "payload"."enum_posts_blocks_image_text_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_image_text" ADD COLUMN "alignment" "payload"."enum_posts_blocks_image_text_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_card_grid" ADD COLUMN "background_style" "payload"."enum_posts_blocks_card_grid_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_card_grid" ADD COLUMN "spacing" "payload"."enum_posts_blocks_card_grid_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_card_grid" ADD COLUMN "alignment" "payload"."enum_posts_blocks_card_grid_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_card_grid" ADD COLUMN "columns" "payload"."enum_posts_blocks_card_grid_columns" DEFAULT '3' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_product_grid" ADD COLUMN "background_style" "payload"."enum_posts_blocks_product_grid_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_product_grid" ADD COLUMN "spacing" "payload"."enum_posts_blocks_product_grid_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_product_grid" ADD COLUMN "alignment" "payload"."enum_posts_blocks_product_grid_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_product_grid" ADD COLUMN "columns" "payload"."enum_posts_blocks_product_grid_columns" DEFAULT '3' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_gallery" ADD COLUMN "background_style" "payload"."enum_posts_blocks_gallery_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_gallery" ADD COLUMN "spacing" "payload"."enum_posts_blocks_gallery_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_gallery" ADD COLUMN "alignment" "payload"."enum_posts_blocks_gallery_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_gallery" ADD COLUMN "columns" "payload"."enum_posts_blocks_gallery_columns" DEFAULT '3' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_downloads" ADD COLUMN "background_style" "payload"."enum_posts_blocks_downloads_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_downloads" ADD COLUMN "spacing" "payload"."enum_posts_blocks_downloads_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_downloads" ADD COLUMN "alignment" "payload"."enum_posts_blocks_downloads_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_downloads" ADD COLUMN "columns" "payload"."enum_posts_blocks_downloads_columns" DEFAULT '3' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_spec_table" ADD COLUMN "background_style" "payload"."enum_posts_blocks_spec_table_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_spec_table" ADD COLUMN "spacing" "payload"."enum_posts_blocks_spec_table_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_spec_table" ADD COLUMN "alignment" "payload"."enum_posts_blocks_spec_table_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_call_to_action" ADD COLUMN "background_style" "payload"."enum_posts_blocks_call_to_action_background_style" DEFAULT 'default' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_call_to_action" ADD COLUMN "spacing" "payload"."enum_posts_blocks_call_to_action_spacing" DEFAULT 'normal' NOT NULL;
  ALTER TABLE "payload"."posts_blocks_call_to_action" ADD COLUMN "alignment" "payload"."enum_posts_blocks_call_to_action_alignment" DEFAULT 'center' NOT NULL;`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "payload"."pages_blocks_hero" DROP COLUMN "background_style";
  ALTER TABLE "payload"."pages_blocks_hero" DROP COLUMN "spacing";
  ALTER TABLE "payload"."pages_blocks_hero" DROP COLUMN "alignment";
  ALTER TABLE "payload"."pages_blocks_rich_text" DROP COLUMN "background_style";
  ALTER TABLE "payload"."pages_blocks_rich_text" DROP COLUMN "spacing";
  ALTER TABLE "payload"."pages_blocks_rich_text" DROP COLUMN "alignment";
  ALTER TABLE "payload"."pages_blocks_image_text" DROP COLUMN "background_style";
  ALTER TABLE "payload"."pages_blocks_image_text" DROP COLUMN "spacing";
  ALTER TABLE "payload"."pages_blocks_image_text" DROP COLUMN "alignment";
  ALTER TABLE "payload"."pages_blocks_card_grid" DROP COLUMN "background_style";
  ALTER TABLE "payload"."pages_blocks_card_grid" DROP COLUMN "spacing";
  ALTER TABLE "payload"."pages_blocks_card_grid" DROP COLUMN "alignment";
  ALTER TABLE "payload"."pages_blocks_card_grid" DROP COLUMN "columns";
  ALTER TABLE "payload"."pages_blocks_product_grid" DROP COLUMN "background_style";
  ALTER TABLE "payload"."pages_blocks_product_grid" DROP COLUMN "spacing";
  ALTER TABLE "payload"."pages_blocks_product_grid" DROP COLUMN "alignment";
  ALTER TABLE "payload"."pages_blocks_product_grid" DROP COLUMN "columns";
  ALTER TABLE "payload"."pages_blocks_gallery" DROP COLUMN "background_style";
  ALTER TABLE "payload"."pages_blocks_gallery" DROP COLUMN "spacing";
  ALTER TABLE "payload"."pages_blocks_gallery" DROP COLUMN "alignment";
  ALTER TABLE "payload"."pages_blocks_gallery" DROP COLUMN "columns";
  ALTER TABLE "payload"."pages_blocks_downloads" DROP COLUMN "background_style";
  ALTER TABLE "payload"."pages_blocks_downloads" DROP COLUMN "spacing";
  ALTER TABLE "payload"."pages_blocks_downloads" DROP COLUMN "alignment";
  ALTER TABLE "payload"."pages_blocks_downloads" DROP COLUMN "columns";
  ALTER TABLE "payload"."pages_blocks_spec_table" DROP COLUMN "background_style";
  ALTER TABLE "payload"."pages_blocks_spec_table" DROP COLUMN "spacing";
  ALTER TABLE "payload"."pages_blocks_spec_table" DROP COLUMN "alignment";
  ALTER TABLE "payload"."pages_blocks_call_to_action" DROP COLUMN "background_style";
  ALTER TABLE "payload"."pages_blocks_call_to_action" DROP COLUMN "spacing";
  ALTER TABLE "payload"."pages_blocks_call_to_action" DROP COLUMN "alignment";
  ALTER TABLE "payload"."posts_blocks_hero" DROP COLUMN "background_style";
  ALTER TABLE "payload"."posts_blocks_hero" DROP COLUMN "spacing";
  ALTER TABLE "payload"."posts_blocks_hero" DROP COLUMN "alignment";
  ALTER TABLE "payload"."posts_blocks_rich_text" DROP COLUMN "background_style";
  ALTER TABLE "payload"."posts_blocks_rich_text" DROP COLUMN "spacing";
  ALTER TABLE "payload"."posts_blocks_rich_text" DROP COLUMN "alignment";
  ALTER TABLE "payload"."posts_blocks_image_text" DROP COLUMN "background_style";
  ALTER TABLE "payload"."posts_blocks_image_text" DROP COLUMN "spacing";
  ALTER TABLE "payload"."posts_blocks_image_text" DROP COLUMN "alignment";
  ALTER TABLE "payload"."posts_blocks_card_grid" DROP COLUMN "background_style";
  ALTER TABLE "payload"."posts_blocks_card_grid" DROP COLUMN "spacing";
  ALTER TABLE "payload"."posts_blocks_card_grid" DROP COLUMN "alignment";
  ALTER TABLE "payload"."posts_blocks_card_grid" DROP COLUMN "columns";
  ALTER TABLE "payload"."posts_blocks_product_grid" DROP COLUMN "background_style";
  ALTER TABLE "payload"."posts_blocks_product_grid" DROP COLUMN "spacing";
  ALTER TABLE "payload"."posts_blocks_product_grid" DROP COLUMN "alignment";
  ALTER TABLE "payload"."posts_blocks_product_grid" DROP COLUMN "columns";
  ALTER TABLE "payload"."posts_blocks_gallery" DROP COLUMN "background_style";
  ALTER TABLE "payload"."posts_blocks_gallery" DROP COLUMN "spacing";
  ALTER TABLE "payload"."posts_blocks_gallery" DROP COLUMN "alignment";
  ALTER TABLE "payload"."posts_blocks_gallery" DROP COLUMN "columns";
  ALTER TABLE "payload"."posts_blocks_downloads" DROP COLUMN "background_style";
  ALTER TABLE "payload"."posts_blocks_downloads" DROP COLUMN "spacing";
  ALTER TABLE "payload"."posts_blocks_downloads" DROP COLUMN "alignment";
  ALTER TABLE "payload"."posts_blocks_downloads" DROP COLUMN "columns";
  ALTER TABLE "payload"."posts_blocks_spec_table" DROP COLUMN "background_style";
  ALTER TABLE "payload"."posts_blocks_spec_table" DROP COLUMN "spacing";
  ALTER TABLE "payload"."posts_blocks_spec_table" DROP COLUMN "alignment";
  ALTER TABLE "payload"."posts_blocks_call_to_action" DROP COLUMN "background_style";
  ALTER TABLE "payload"."posts_blocks_call_to_action" DROP COLUMN "spacing";
  ALTER TABLE "payload"."posts_blocks_call_to_action" DROP COLUMN "alignment";
  DROP TYPE "payload"."enum_pages_blocks_hero_background_style";
  DROP TYPE "payload"."enum_pages_blocks_hero_spacing";
  DROP TYPE "payload"."enum_pages_blocks_hero_alignment";
  DROP TYPE "payload"."enum_pages_blocks_rich_text_background_style";
  DROP TYPE "payload"."enum_pages_blocks_rich_text_spacing";
  DROP TYPE "payload"."enum_pages_blocks_rich_text_alignment";
  DROP TYPE "payload"."enum_pages_blocks_image_text_background_style";
  DROP TYPE "payload"."enum_pages_blocks_image_text_spacing";
  DROP TYPE "payload"."enum_pages_blocks_image_text_alignment";
  DROP TYPE "payload"."enum_pages_blocks_card_grid_background_style";
  DROP TYPE "payload"."enum_pages_blocks_card_grid_spacing";
  DROP TYPE "payload"."enum_pages_blocks_card_grid_alignment";
  DROP TYPE "payload"."enum_pages_blocks_card_grid_columns";
  DROP TYPE "payload"."enum_pages_blocks_product_grid_background_style";
  DROP TYPE "payload"."enum_pages_blocks_product_grid_spacing";
  DROP TYPE "payload"."enum_pages_blocks_product_grid_alignment";
  DROP TYPE "payload"."enum_pages_blocks_product_grid_columns";
  DROP TYPE "payload"."enum_pages_blocks_gallery_background_style";
  DROP TYPE "payload"."enum_pages_blocks_gallery_spacing";
  DROP TYPE "payload"."enum_pages_blocks_gallery_alignment";
  DROP TYPE "payload"."enum_pages_blocks_gallery_columns";
  DROP TYPE "payload"."enum_pages_blocks_downloads_background_style";
  DROP TYPE "payload"."enum_pages_blocks_downloads_spacing";
  DROP TYPE "payload"."enum_pages_blocks_downloads_alignment";
  DROP TYPE "payload"."enum_pages_blocks_downloads_columns";
  DROP TYPE "payload"."enum_pages_blocks_spec_table_background_style";
  DROP TYPE "payload"."enum_pages_blocks_spec_table_spacing";
  DROP TYPE "payload"."enum_pages_blocks_spec_table_alignment";
  DROP TYPE "payload"."enum_pages_blocks_call_to_action_background_style";
  DROP TYPE "payload"."enum_pages_blocks_call_to_action_spacing";
  DROP TYPE "payload"."enum_pages_blocks_call_to_action_alignment";
  DROP TYPE "payload"."enum_posts_blocks_hero_background_style";
  DROP TYPE "payload"."enum_posts_blocks_hero_spacing";
  DROP TYPE "payload"."enum_posts_blocks_hero_alignment";
  DROP TYPE "payload"."enum_posts_blocks_rich_text_background_style";
  DROP TYPE "payload"."enum_posts_blocks_rich_text_spacing";
  DROP TYPE "payload"."enum_posts_blocks_rich_text_alignment";
  DROP TYPE "payload"."enum_posts_blocks_image_text_background_style";
  DROP TYPE "payload"."enum_posts_blocks_image_text_spacing";
  DROP TYPE "payload"."enum_posts_blocks_image_text_alignment";
  DROP TYPE "payload"."enum_posts_blocks_card_grid_background_style";
  DROP TYPE "payload"."enum_posts_blocks_card_grid_spacing";
  DROP TYPE "payload"."enum_posts_blocks_card_grid_alignment";
  DROP TYPE "payload"."enum_posts_blocks_card_grid_columns";
  DROP TYPE "payload"."enum_posts_blocks_product_grid_background_style";
  DROP TYPE "payload"."enum_posts_blocks_product_grid_spacing";
  DROP TYPE "payload"."enum_posts_blocks_product_grid_alignment";
  DROP TYPE "payload"."enum_posts_blocks_product_grid_columns";
  DROP TYPE "payload"."enum_posts_blocks_gallery_background_style";
  DROP TYPE "payload"."enum_posts_blocks_gallery_spacing";
  DROP TYPE "payload"."enum_posts_blocks_gallery_alignment";
  DROP TYPE "payload"."enum_posts_blocks_gallery_columns";
  DROP TYPE "payload"."enum_posts_blocks_downloads_background_style";
  DROP TYPE "payload"."enum_posts_blocks_downloads_spacing";
  DROP TYPE "payload"."enum_posts_blocks_downloads_alignment";
  DROP TYPE "payload"."enum_posts_blocks_downloads_columns";
  DROP TYPE "payload"."enum_posts_blocks_spec_table_background_style";
  DROP TYPE "payload"."enum_posts_blocks_spec_table_spacing";
  DROP TYPE "payload"."enum_posts_blocks_spec_table_alignment";
  DROP TYPE "payload"."enum_posts_blocks_call_to_action_background_style";
  DROP TYPE "payload"."enum_posts_blocks_call_to_action_spacing";
  DROP TYPE "payload"."enum_posts_blocks_call_to_action_alignment";`)
}
