/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'console-users': ConsoleUserAuthOperations;
  };
  blocks: {};
  collections: {
    'console-users': ConsoleUser;
    media: Media;
    documents: Document;
    'product-categories': ProductCategory;
    products: Product;
    themes: Theme;
    'page-templates': PageTemplate;
    menus: Menu;
    pages: Page;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'console-users': ConsoleUsersSelect<false> | ConsoleUsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    'page-templates': PageTemplatesSelect<false> | PageTemplatesSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'theme-settings': ThemeSetting;
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
  };
  globalsSelect: {
    'theme-settings': ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: ConsoleUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface ConsoleUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "console-users".
 */
export interface ConsoleUser {
  id: number;
  name?: string | null;
  /**
   * Use Admin for now. Editor is available for future limited-access accounts.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'console-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  /**
   * Lowercase URL segment. Use letters, numbers and hyphens.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Lowercase URL segment. Use letters, numbers and hyphens.
   */
  slug: string;
  status: 'draft' | 'published';
  featured?: boolean | null;
  category?: (number | null) | ProductCategory;
  family: string;
  template: 'hmi' | 'data-logger' | 'module';
  summary: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  gallery?: (number | Media)[] | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  documents?: (number | Document)[] | null;
  variants?:
    | {
        name: string;
        details?: string | null;
        sku?: string | null;
        articleNumber?: string | null;
        price?: string | null;
        id?: string | null;
      }[]
    | null;
  enquiryPrompt: string;
  /**
   * Optional search/social metadata. Leave blank to use the page title and summary.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: number;
  name: string;
  /**
   * Short theme key used by the WYSIWYG editor.
   */
  handle: string;
  status: 'active' | 'draft';
  /**
   * Used when a page does not have a theme selected.
   */
  isDefault?: boolean | null;
  description?: string | null;
  colors: {
    backgroundColor: string;
    textColor: string;
    accentColor: string;
    /**
     * RGB values, for example: 23, 32, 51.
     */
    surfaceColor: string;
    surfaceOpacity: number;
  };
  typography: {
    fontFamily: 'display' | 'sans' | 'code';
  };
  layout: {
    sectionSpacing: 'compact' | 'normal' | 'spacious';
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-templates".
 */
export interface PageTemplate {
  id: number;
  name: string;
  /**
   * Short template key used by the whole-site template selector.
   */
  handle: string;
  status: 'active' | 'draft';
  description?: string | null;
  /**
   * Default theme to use when this website template is selected.
   */
  theme?: (number | null) | Theme;
  /**
   * Reusable WYSIWYG layout data used as the starting point for this website template.
   */
  builderData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  name: string;
  /**
   * Short key used by the WYSIWYG editor, for example main-menu or footer-links.
   */
  handle: string;
  /**
   * Add, remove, rename and reorder the links in this menu.
   */
  items?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Lowercase URL segment. Use letters, numbers and hyphens.
   */
  slug: string;
  /**
   * Short internal/search summary.
   */
  summary?: string | null;
  /**
   * Theme used by the new Payload/WYSIWYG site.
   */
  theme?: (number | null) | Theme;
  /**
   * Website template this page was created from. Optional; existing pages can stay independent.
   */
  pageTemplate?: (number | null) | PageTemplate;
  status: 'draft' | 'published';
  layout: (
    | {
        eyebrow?: string | null;
        heading: string;
        lede?: string | null;
        image?: (number | null) | Media;
        primaryLink?: {
          label?: string | null;
          url?: string | null;
        };
        secondaryLink?: {
          label?: string | null;
          url?: string | null;
        };
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        heading: string;
        body?: string | null;
        image: number | Media;
        imageSide: 'left' | 'right';
        link?: {
          label?: string | null;
          url?: string | null;
        };
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageText';
      }
    | {
        heading: string;
        intro?: string | null;
        cards?:
          | {
              title: string;
              body?: string | null;
              link?: {
                label?: string | null;
                url?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        columns: '2' | '3' | '4';
        id?: string | null;
        blockName?: string | null;
        blockType: 'cardGrid';
      }
    | {
        heading: string;
        intro?: string | null;
        mode: 'featured' | 'manual';
        products?: (number | Product)[] | null;
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        columns: '2' | '3' | '4';
        id?: string | null;
        blockName?: string | null;
        blockType: 'productGrid';
      }
    | {
        heading?: string | null;
        images: (number | Media)[];
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        columns: '2' | '3' | '4';
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        heading: string;
        documents?: (number | Document)[] | null;
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        columns: '2' | '3' | '4';
        id?: string | null;
        blockName?: string | null;
        blockType: 'downloads';
      }
    | {
        heading: string;
        rows?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        id?: string | null;
        blockName?: string | null;
        blockType: 'specTable';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        body?: string | null;
        primaryLink?: {
          label?: string | null;
          url?: string | null;
        };
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        id?: string | null;
        blockName?: string | null;
        blockType: 'callToAction';
      }
  )[];
  /**
   * Visual builder data generated by the Console WYSIWYG editor. Leave blank to use the structured Payload blocks.
   */
  builderData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Optional search/social metadata. Leave blank to use the page title and summary.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Lowercase URL segment. Use letters, numbers and hyphens.
   */
  slug: string;
  summary: string;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  featuredImage?: (number | null) | Media;
  layout: (
    | {
        eyebrow?: string | null;
        heading: string;
        lede?: string | null;
        image?: (number | null) | Media;
        primaryLink?: {
          label?: string | null;
          url?: string | null;
        };
        secondaryLink?: {
          label?: string | null;
          url?: string | null;
        };
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        heading: string;
        body?: string | null;
        image: number | Media;
        imageSide: 'left' | 'right';
        link?: {
          label?: string | null;
          url?: string | null;
        };
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageText';
      }
    | {
        heading: string;
        intro?: string | null;
        cards?:
          | {
              title: string;
              body?: string | null;
              link?: {
                label?: string | null;
                url?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        columns: '2' | '3' | '4';
        id?: string | null;
        blockName?: string | null;
        blockType: 'cardGrid';
      }
    | {
        heading: string;
        intro?: string | null;
        mode: 'featured' | 'manual';
        products?: (number | Product)[] | null;
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        columns: '2' | '3' | '4';
        id?: string | null;
        blockName?: string | null;
        blockType: 'productGrid';
      }
    | {
        heading?: string | null;
        images: (number | Media)[];
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        columns: '2' | '3' | '4';
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        heading: string;
        documents?: (number | Document)[] | null;
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        columns: '2' | '3' | '4';
        id?: string | null;
        blockName?: string | null;
        blockType: 'downloads';
      }
    | {
        heading: string;
        rows?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        id?: string | null;
        blockName?: string | null;
        blockType: 'specTable';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        body?: string | null;
        primaryLink?: {
          label?: string | null;
          url?: string | null;
        };
        backgroundStyle: 'default' | 'panel' | 'soft' | 'contrast';
        spacing: 'compact' | 'normal' | 'spacious';
        alignment: 'left' | 'center';
        id?: string | null;
        blockName?: string | null;
        blockType: 'callToAction';
      }
  )[];
  /**
   * Optional search/social metadata. Leave blank to use the page title and summary.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'console-users';
        value: number | ConsoleUser;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'themes';
        value: number | Theme;
      } | null)
    | ({
        relationTo: 'page-templates';
        value: number | PageTemplate;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'console-users';
    value: number | ConsoleUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'console-users';
    value: number | ConsoleUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "console-users_select".
 */
export interface ConsoleUsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  featured?: T;
  category?: T;
  family?: T;
  template?: T;
  summary?: T;
  description?: T;
  gallery?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  documents?: T;
  variants?:
    | T
    | {
        name?: T;
        details?: T;
        sku?: T;
        articleNumber?: T;
        price?: T;
        id?: T;
      };
  enquiryPrompt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  name?: T;
  handle?: T;
  status?: T;
  isDefault?: T;
  description?: T;
  colors?:
    | T
    | {
        backgroundColor?: T;
        textColor?: T;
        accentColor?: T;
        surfaceColor?: T;
        surfaceOpacity?: T;
      };
  typography?:
    | T
    | {
        fontFamily?: T;
      };
  layout?:
    | T
    | {
        sectionSpacing?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-templates_select".
 */
export interface PageTemplatesSelect<T extends boolean = true> {
  name?: T;
  handle?: T;
  status?: T;
  description?: T;
  theme?: T;
  builderData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  name?: T;
  handle?: T;
  items?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  theme?: T;
  pageTemplate?: T;
  status?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              lede?: T;
              image?: T;
              primaryLink?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryLink?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              imageSide?: T;
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              heading?: T;
              intro?: T;
              cards?:
                | T
                | {
                    title?: T;
                    body?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              heading?: T;
              intro?: T;
              mode?: T;
              products?: T;
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?: T;
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        downloads?:
          | T
          | {
              heading?: T;
              documents?: T;
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        specTable?:
          | T
          | {
              heading?: T;
              rows?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              primaryLink?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
      };
  builderData?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  status?: T;
  publishedAt?: T;
  featuredImage?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              lede?: T;
              image?: T;
              primaryLink?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryLink?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              imageSide?: T;
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              heading?: T;
              intro?: T;
              cards?:
                | T
                | {
                    title?: T;
                    body?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              heading?: T;
              intro?: T;
              mode?: T;
              products?: T;
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?: T;
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        downloads?:
          | T
          | {
              heading?: T;
              documents?: T;
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        specTable?:
          | T
          | {
              heading?: T;
              rows?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              primaryLink?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              backgroundStyle?: T;
              spacing?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: number;
  /**
   * The active whole-website template for the new Payload-built Eltronic site.
   */
  activeTemplate?: (number | null) | PageTemplate;
  /**
   * The default visual theme used when a page does not have its own override.
   */
  activeTheme?: (number | null) | Theme;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  strapline?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  logo?: (number | null) | Media;
  /**
   * Optional search/social metadata. Leave blank to use the page title and summary.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  primary?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  utility?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  intro?: string | null;
  linkGroups?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  activeTemplate?: T;
  activeTheme?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  strapline?: T;
  contactEmail?: T;
  contactPhone?: T;
  logo?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  utility?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  intro?: T;
  linkGroups?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}